# Generated by Django 5.2.3 on 2025-06-22 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='explorarmodel',
            old_name='nome',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='explorarmodel',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='explorarmodel',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
