# Generated by Django 5.2.3 on 2025-06-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorar', '0002_rename_nome_explorarmodel_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorarmodel',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='explorar_fotos/'),
        ),
        migrations.AlterField(
            model_name='explorarmodel',
            name='data_criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
